### ISSUE TITLE
crash when inserting or removing yubikey

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ios#1157]
### Description: 
Browser crash when security key is quickly connected/disconnected

### Steps to Reproduce 
  1. Login to a site that supports security key
  2. When site asks for security key, quickly connect and then immediately disconnect the key
  3. Browser crashes without logging into the site
  4. Relaunch app, tab from step 1 is lost
https://bravesoftware.slack.com/archives/GK85STQT0/p1560799414016000

**Actual result:** 
Browser crash when security key is quickly connected/disconnected

**Expected result:**
No crash should happen when security key is quickly connected/disconnected

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Device details:** 
iPhone 7+ (iOS 12.3.1)

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by kjozwiak** [comment]
@jumde @tomlowenthal is there any plans on working on WebAuth and fixing these remaining issues? I'm seeing the above crash pretty often when we're running through our manual passes. Brave basically crashes when you remove the YubiKey in certain cases while it's being used to authenticate.

I've also ran into cases where loading a website that's requesting WebAuth will crash Brave instantly. It usually takes visiting the same website ~2-3 times before it stops crashing. I'm not sure how many people are actually using YubiKeys so it might not be urgent.

Probably worth checking if we can get some crash numbers that are related to YubiKey.

**Comment by jumde** [comment]
@kjozwiak - I thought these issues were addressed, will try repro'ing the issues with the latest build. If you have any quick repro steps, that'll be helpful.

**Comment by jumde** [comment]
@srirambv @kjozwiak - Tried connecting and disconnecting the keys on demo.yubico.com/u2f very fast. No crashes.

**Comment by kjozwiak** [comment]
@jumde it's definitely still happening pretty often. Here's some more info that might help reproduce the issue:

* Using `YubiKey 5Ci` with `FW 5.2.3`
* `iPhone 6s+ running iOS 12.4.1` using `1.16 (20.05.07.16)` - **Reproduced**
* `iPhone 11 running iOS 13.4.1` using `1.16 (20.05.07.16)` - - **Reproduced**

@jumde here's what I basically do to reproduce the crash mentioned above:

* install `1.16 (20.05.07.16)`
* log into an GH account that has a YubiKey associated with it
* plug/unplug the YubiKey via the lighting port several times (sometimes it will crash here)
* after you've unplugged/plugged it a few times, complete the WebAuth and login
* switch over the private browsing and basically do the same thing (crashes here sometimes)
* switch over from PB -> normal mode and unplug the YubiKey (crashes pretty often here)

Usually following the above will reproduce a crash here and there. Example:

* https://youtu.be/d2eAaOpa7lQ

**Comment by kjozwiak** [comment]
Still an issue and ran into when running through `1.22 (20.12.2.1)`.

**Comment by kjozwiak** [comment]
@jumde added some stack traces that might be of help to finally narrow this down. You'll probably need to symbolize them though.

Crashes while using `iPad Mini 4` running `iOS 13.7`:

* [Client-2021-05-04-163057.ips.beta.txt](https://github.com/brave/brave-ios/files/6423824/Client-2021-05-04-163057.ips.beta.txt)
* [Client-2021-05-04-162447.ips.beta.txt](https://github.com/brave/brave-ios/files/6423825/Client-2021-05-04-162447.ips.beta.txt)

Crashes while using `iPhone 11` running `iOS 14.5.1`:

* [Client-2021-05-04-165437.ips.beta.txt](https://github.com/brave/brave-ios/files/6423906/Client-2021-05-04-165437.ips.beta.txt)
* [Client-2021-05-04-165047.ips.beta.txt](https://github.com/brave/brave-ios/files/6423909/Client-2021-05-04-165047.ips.beta.txt)

@jumde let me know if you need anymore info 👍

**Comment by kjozwiak** [comment]
Closing as we've deprecated the `Yubikey` SDK in favour of the `WKWebView` SDK as per https://github.com/brave/brave-ios/issues/4473. QA went through verifications via https://github.com/brave/brave-ios/issues/4473#issuecomment-1032291511, https://github.com/brave/brave-ios/issues/4473#issuecomment-1033102239 & https://github.com/brave/brave-ios/issues/4473#issuecomment-1033240109 and couldn't reproduce the crashes using the `WKWebView` SDK.
