### ISSUE TITLE
Fullscreen Video not  Fullscreen anymore on Ipad.

### ISSUE THREAD

**Issue by VimS** [brave/brave-ios#1194]
### Description: 
Fullscreen-Video-Playback on iPad is not working for me anymore.
Befor the last update I was able to watch Videos in Brave in total Fullscreen-mode, now the Browser is still showing and touchcontrolle are wonky and have changed.

### Steps to Reproduce 
  1. go to a Video-Site eg. youtube.com 
  2. watch a Video
  3. Turn on fullscreen

**Actual result:**
Browser-controlls, tabbar and adressbar are still showing.
youtube adds an anchor #fauxfullscreen to the URL

**Expected result:**
Video should use the FULL screen, touch controlls should be working e.g. one touch on the Video to show controlls etc.

**Reproduces how often:** 
Easily reproduced

**Brave Version:**
iPad
Version 1.9.3 (19.05.22.15)

**Device details:** 
Apple Ipad MR7J2FD/A
iOS 12.3.1

**Website problems only:**
- did you check with Brave Shields down? yup, changed nothing
- did you check in Safari/Firefox (WkWebView-based browsers)? 
In Safari it works, Firefox shows the same behaviour.

**Comment by srirambv** [comment]
This is the same behaviour on Firefox and a known issue. Not sure if we want to fix it ourselves or wait for the upstream fix. 

cc: @jhreis @danishjafri88 @anthonypkeane

**Comment by anthonypkeane** [comment]
We should fix this

**Comment by kylehickinson** [comment]
Cannot reproduce in iOS 12 or 13

**Comment by alindco** [comment]
I don’t know why this is closed. It still happens all the time just like the steps explained

**Comment by Brandon-T** [comment]
@alindco 

Mobile site:
https://i.imgur.com/QgATyaT.mp4

Desktop site:
https://i.imgur.com/iR1hjwv.mp4

Tested on iPad OS 12.2 & 12.4 & 13.3 on various websites.

I am not experiencing this issue.
Do you happen to have a specific web-page where the fullscreen is not working?
Are you using the latest version of Brave?

Thanks in advanced.

**Comment by alindco** [comment]
Do not be discouraged 
Learning is a life time activity.
