### ISSUE TITLE
iPad dark mode issue with tab color

### ISSUE THREAD

**Issue by phoogm** [brave/brave-ios#2558]
### Description: 
When iOS for iPad switches from light to dark mode automatically the tab color does not adjust itself other then after closing and re-opening the Brave browser.

### Steps to Reproduce 
  1.  Launch Brave browser on iOS
  2. Switch from light to dark mode or reverse
  3. Observe the tab color to stay in light mode when iOS is in dark mode or reverse

**Actual result:** 
![IMG_0029](https://user-images.githubusercontent.com/56597375/82122242-9a6bd900-9792-11ea-958f-06a756747d14.jpg)

**Expected result:**
Switching from light to dark mode or reverse should cause all visible browser elements to follow the mode when the appearance is set to automatic.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easily reproduced

**Brave Version:** 
1.16.1(20.05.14.20)

**Device details:** 
iPad Pro 12.9 inch 3rd generation (iOS 13.4.1)

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A 

### Additional Information
Thanks for looking into this. Best regards.

**Comment by hennrynusasatria** [comment]
Hi @phoogm @jhreis @kylehickinson @iccub 

Is this issue the same as on #2733 ? Does it mean it is already fixed and closed?

Thank you.

**Comment by kylehickinson** [comment]
@hennrynusasatria No, that issue was for the tab tray not the tab bar 🙂 This issue is still not fixed

**Comment by srirambv** [comment]
Verification passed on iPad Pro with iOS 14.4 running 1.23(21.1.28.16)
- Verified changing theme via control centre changes the entire UI 
-------------
Verification passed on iPhone 7+ with iOS 14.4 running 1.23(21.1.28.16)
- Verified changing theme via control centre changes the entire UI 
-------------
Verification passed on iPhone XR with iOS 13.5 running 1.23(21.1.28.16)
- Verified changing theme via control centre changes the entire UI 
-------------
Logged #3243 as a followup

**Comment by iccub** [comment]
We have to pull it back from this milestone, will be revisited later, hopefully after we drop iOS 12

**Comment by srirambv** [comment]
Blocked on #3549

**Comment by srirambv** [comment]
Verification passed on iPhone 7+ with iOS 14.4.2 running 1.25(21.4.21.15)
- Verified switching theme via control centre doesn't affect the tab bar theme

https://user-images.githubusercontent.com/17010094/116071944-64172900-a686-11eb-897e-20168ed8ca5e.MP4

-----------
Verification passed on iPhone XR with iOS 13.5 running 1.25(21.4.21.15)
- Verified switching theme via control centre doesn't affect the tab bar theme

https://user-images.githubusercontent.com/17010094/116071170-7ba1e200-a685-11eb-868f-c2ac5b0beb45.MP4

-----------
Verification passed on iPhone iPad Pro with iOS 14.4.2 running 1.25(21.4.21.15)
- Verified switching theme via control centre doesn't affect the tab bar theme

https://user-images.githubusercontent.com/17010094/116071231-8a889480-a685-11eb-8cd3-873e9f66a017.MP4

**Comment by kjozwiak** [comment]
Changing from `release-notes/exclude` to `release-notes/include`  as we changed/added new UI to the legacy wallet transfer feature which is user facing.
