### ISSUE TITLE
unable to import bookmarks on iPad if bookmark file is not named Bookmarks.html

### ISSUE THREAD

**Issue by LaurenWags** [brave/brave-ios#3004]
### Description: 
Tried importing bookmarks file on iPad w/ iOS13 and bookmarks were not imported. No error message or visible reason as to why.

### Steps to Reproduce 

1. Install 1.20 from Dev TF
1. Setup bookmarks/folders/subfolders
1. Upgrade to latest 1.21 on Dev TF
1. Wait at least 1 minute
1. View the Files on my iPad (under Brave Dev there was a Bookmarks file that I guess the upgrade creates automatically?) --> sent this file to my laptop to have a copy (rename from Bookmarks.html to something else like `Bookmarks-created on upgrade - Step 5.html`)
1. Check 1.21 to confirm bookmarks are visible as expected :white_check_mark: 
1. Export bookmarks to Files (just wanted to compare this to the one created on upgrade) --> sent this file to my laptop to have a copy (Rename from Bookmarks.html to something else like `Bookmarks-manually exported after upgrade - Step 7.html`)
1. Deleted 1.21
1. Clean install 1.21
1. Sent renamed bookmarks from step 5 to iPad
1. Tried to import this file --> bookmarks not imported

**Actual result:** 
Unable to import file from step 5 or 7, no indication of why on screen

**Expected result:**
bookmarks imported

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100% on my device w/ above steps

**Brave Version:** 
1.21 (20.10.30.21)

**Device details:** 
iPad iOS13

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

**Comment by iccub** [comment]
Should be fixed in `Brave Dev 1.21 (20.11.2.17)` please retest

**Comment by LaurenWags** [comment]
Still reproduces on iOS13 iPad mini using `Brave Dev 1.21 (20.11.2.17)`

**Comment by LaurenWags** [comment]
Digging a bit more, seems if I have a file named `Bookmarks.html` it will import w/o issue, but if I rename the bookmarks file, it does not import and does not give any sort of failure notification. Thanks @Brandon-T for providing video so I could spot the differences in what I was doing 👍

**Comment by iccub** [comment]
Please retest in `Brave Dev 1.21 (20.11.2.20)`

**Comment by LaurenWags** [comment]
Verification passed on iPad mini with iOS 13 running 1.21 (20.11.02.20)

- Confirmed able to import file named `Bookmarks-created on upgrade - Step 5.html` without issue. Confirmed after import bookmarks appeared as expected.

![IMG_10DCB101A9C7-1](https://user-images.githubusercontent.com/28145373/98019591-f291a880-1dcf-11eb-8da9-7167aceefba5.jpeg)

-----------

Verification passed on iPhone 7+ with iOS 14.1 running 1.21(20.11.2.20)
- Verified able to import bookmarks when custom file name is used
-------------
Verification passed on iPhone XR with iOS 13.5 running 1.21(20.11.2.20)
- Verified able to import bookmarks when custom file name is used
