### ISSUE TITLE
Share loaded document with Archives not an option

### ISSUE THREAD

**Issue by parsd51** [brave/brave-ios#3313]
### Description: 
Share loaded document with Archives not an option on iPad.

### Steps to Reproduce 
  1. Open (just an example): https://www.trm.dk/media/5076/anlaegsstatus-2-halvaar-2020.pdf
  2. Press ... and then Share with..
  3.

**Actual result:** 
Not possible to share with/save to Archives on iPad

**Expected result:**
Possibility to share with/save to Archives on iPad

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
100%

**Brave Version:** 
Brave iPadOS 1.23 (21.2.12.22)

**Device details:** 
iPad Air 2, iPadOS 14.4

**Website problems only:**
- did you check with Brave Shields down? N/A
- did you check in Safari/Firefox (WkWebView-based browsers)? N/A

**Comment by iccub** [comment]
This should be resolved now

**Comment by parsd51** [comment]
Still reproduceable on my iPad Air 4, iPadOS 14.7.1, Brave 130.1 released version.
Archives not shown as option.
Options in https://github.com/brave/brave-ios/issues/3323 are not shown.

**Comment by RonanCodes** [comment]
I also still have this issue. iPad Air 4. iOS 14.6. Brave Version 1.30.1 (21.8.17.19)
