### ISSUE TITLE
tapping on "switch" at the bottom while Brave is transitioning into PB leaves browser in weird state

### ISSUE THREAD

**Issue by kjozwiak** [brave/brave-ios#777]
### Description: 

When you tap on the `Switch` modal at the bottom of the screen while you're also about to transition in PB, Brave gets stuck in this strange state where it's in PB but thinks it's in regular mode until you open a new tab. When you're in this state, you'll notice that the tab bar is completely cleared.

This is pretty edge case and requires good timing. I'm not sure a user would run into this but worth looking into to see what's going on as it involves PB.

### Steps to Reproduce 

  1. open brave and load https://en.wikipedia.org/wiki/Main_Page
  2. tap on a link and select `Open in New Tab` (should see the `Switch` blue modal at the bottom)
  3. while the `Switch` modal is visible, tap on the same link and select `Open in New Private Tab`
  4. quickly tap on the `Switch` button on the blue modal while Brave is attempting to switch to PB

**Actual result:** 

Example of issue --> https://youtu.be/VCQLJLV4sbc

**Expected result:**

Users shouldn't be able to get into the strange state.

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100% reproducible when you nail down the timing.

**Brave Version:** 

* `1.7.3 (19.1.22.17)` - Reproduced
* `1.7.2 (19.1.18.15)` - Reproduced

**Device details:** 

* Used `iPad Mini 4 running iOS 12.1.3` & `iPhone 6s+ running  iOS 12.1.3`

**Website problems only:**
- did you check with Brave Shields down?

N/A

- did you check in Safari/Firefox (WkWebView-based browsers)? 

N/A

**Comment by srirambv** [comment]
This is actually pretty easy to reproduce and very hard to come out of private tab once its switched. Can't open tab tray to exit private mode. Only option is to remove app from memory and relaunch

**Comment by jhreis** [comment]
@srirambv Can you retest this please?

**Comment by srirambv** [comment]
Just tried on beta 1.12 and this doesn't reproduce on iPhone. However on iPad with Appstore build, I ran into crash thrice and the issue was reproduced. Steps are as follows
1. Open Wikipedia link
2. Long press on a link and open in a new tab
3. Long press on the same link and open in a private tab
4. Tap on Switch button
5. Shows only 1 tab which looks like normal tab but is actually a private tab
6. Tap on new tab button opens a new private tab
7. Close all private tabs and tap on `Private` to exit private mode, browser crashes

**Comment by srirambv** [comment]
Update: Reproduced the crash on iPhone running the Appstore version. There's no crash on 1.12 beta however it still has the missing tab in private mode

**Comment by iccub** [comment]
Should be fixed with the latest NTP refactor, closing this and adding to 1.20 to retest it

**Comment by kjozwiak** [comment]
I can still reproduce the above issue using the STR/cases outlined via https://github.com/brave/brave-ios/issues/777#issue-402014289 while using `1.21 (20.09.30.20)`.

* `iPhone 11` running `iOS 14.0.1` using `1.21 (20.09.30.20)` - **Reproduced**
* `iPad Air (3rd Gen)` running `iOS 14.0.1` using `1.21 (20.09.30.20)` - **Reproduced**

However, I couldn't reproduce the crash @srirambv mentioned via https://github.com/brave/brave-ios/issues/777#issuecomment-519480478. Re-opening and removing the `1.21` milestone as this wasn't fixed during the NTP refactor.

**Comment by iccub** [comment]
we refactored PB mode recently, this should work now
