### ISSUE TITLE
Unblinded payment tokens are not redeemed

### ISSUE THREAD

**Issue by Uni-verse** [brave/brave-ios#8093]
### Description: 
Unblinded payment tokens are not redeemed, reproducible on 1.57, 1.57.1

Related to: https://github.com/brave/brave-browser/issues/32991

![Screenshot 2023-09-19 at 2 17 20 PM](https://github.com/brave/brave-ios/assets/17885425/7521520a-29f6-46b3-bfbd-a3a39fb69154)

### Steps to Reproduce 
  1. Enable Brave Rewards
  2. Wait for a ad to show up and monitor logs
  3. Confirm view confirmation in console and confirm token redeem schedule
  4. Kill Brave app
  5. Move time forward to token redeem window
  6. Open brave, monitor logs

### Actual result: 
payment tokens are not redeemed, keeps showing payment tokens will be redeemed in 0 hours, 0 minutes, 0 seconds at 19:00:00:000

### Expected result:
Should be redeemed

### Reproduces how often: [Easily reproduced, Intermittent Issue]
Easily

### Brave Version:  

1.57 (23.9.4.13)
1.57.1 (23.9.18.13)

- Can you reproduce this issue with the most recent build from TestFlight? Yes
- Can you reproduce this issue with the previous version of the current build from TestFlight? Yes
- Can you reproduce this issue with the current build from AppStore? Yes

### Device details: 
iPad, iPhone

**Comment by Uni-verse** [comment]
This should be resolved by https://github.com/brave/brave-browser/issues/32991

**Comment by iccub** [comment]
@Uni-verse let's close and retest in 1.58?

**Comment by kjozwiak** [comment]
@Uni-verse @hffvld moving this into the `1.58` milestone so we can check/verify that the above is either working/or needs to get fixed/addressed.

**Comment by iccub** [comment]
Fixed in latest build, please retest

**Comment by Uni-verse** [comment]
> Fixed in latest build, please retest

Tested this using 1.58 (23.10.17.8) on iPhone 12 running iOS 17. This is still unresolved as I still see the original behavior. I created a follow up issue https://github.com/brave/brave-ios/issues/8273

cc: @kjozwiak
